/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.validation

import dk.sdu.mmmi.mdsd.math.Var
import dk.sdu.mmmi.mdsd.math.MathPackage
import org.eclipse.xtext.validation.Check
import dk.sdu.mmmi.mdsd.math.Program
import dk.sdu.mmmi.mdsd.math.Type

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MathValidator extends AbstractMathValidator {
	
	public static final String VAR_UNIQUE = 'var_unique'
	
	@Check
	def void uniqueGlobalVariableDefinition(Var binding){
		if((binding.eContainer as Program).exp.filter[name == binding.name].size > 1)
			error("Duplicate global variable", MathPackage.eINSTANCE.binding_Name, VAR_UNIQUE)
	}
	
	@Check
	def void validType(Type type) {
		if (!(type.name == 'int' || type.name == 'float' || type.name == 'bool')) {
			error(type.name + " is not a valid datatype", MathPackage.Literals.TYPE__NAME)
		}
	}
}
