/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Par</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Par#getParen <em>Paren</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getPar()
 * @model
 * @generated
 */
public interface Par extends Exp
{
  /**
   * Returns the value of the '<em><b>Paren</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paren</em>' containment reference.
   * @see #setParen(Exp)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getPar_Paren()
   * @model containment="true"
   * @generated
   */
  Exp getParen();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Par#getParen <em>Paren</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Paren</em>' containment reference.
   * @see #getParen()
   * @generated
   */
  void setParen(Exp value);

} // Par
